In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])
print(x*y)

tensor([10.,  3.])


In [4]:
x= torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
y = torch.rand([2,5])
print(y,y.shape)

tensor([[0.0858, 0.4756, 0.6507, 0.8394, 0.5452],
        [0.3954, 0.2450, 0.6900, 0.0814, 0.9365]]) torch.Size([2, 5])
